name: callme
on:
  workflow_dispatch:
    
  #workflow_call
jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - run: |
            echo callme
        #    echo "$(basename${{github.repository}})"
