name: java-maven

on:
  workflow_call:
    inputs: 
      java-version:
        required: true
        type: string
      node-version:
        required: true
        type: string
      
  
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '${{ inputs.java-version }}'
          distribution: 'adopt'
      - uses: actions/setup-node@v3
        with:
          node-version: '${{ inputs.node-version }}'
    
      - name: Install dependencies
        run: |
          apt-get update
          apt install maven -y
          apt-get update
          mvn -version
          mvn -B package --file pom.xml
          mkdir artifact && cp target/*.jar artifact
          npm ci
          npm test
      - name: maven version
        run: mvn -version
      - name: upload arifacts
        uses: actions/upload-artifact@v2
        with:
         name: artifacts
         path: artifact
         retention-days: 90
